// Top-level build file
buildscript {
    repositories {
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.10'
        classpath 'org.jetbrains.kotlin:kotlin-serialization:1.9.10'
    }
}

allprojects {
    repositories {
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}