org.gradle.jvmargs=-Xmx2g -Xms1g -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Disable SDK update checks to avoid network timeouts
android.builder.sdkDownload=false